Switch from bun to nodejs/yarn
Kept getting the following error when running `bun run watch:css`:

```
$ nodemon --watch ./app/assets/stylesheets/ --ext scss --exec \"bun run build:css\"
[nodemon] 3.0.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): app/assets/stylesheets/**/*
[nodemon] watching extensions: scss
[nodemon] starting `"bun run build:css"`
Error: Invalid stdio option "[object EventEmitter]"
    at <anonymous> (node:child_process:355:24)
    at map (:1:11)
    at spawn (node:child_process:610:8)
    at <anonymous> (node:child_process:2:21)
    at run (/Users/david/Documents/Development/card-board/node_modules/nodemon/lib/monitor/run.js:146:23)
    at <anonymous> (/Users/david/Documents/Development/card-board/node_modules/nodemon/lib/nodemon.js:243:9)
    at <anonymous> (/Users/david/Documents/Development/card-board/node_modules/nodemon/lib/config/index.js:82:7)
    at processTicksAndRejections (:61:39)
error: Invalid stdio option "[object EventEmitter]"
      at node:child_process:356:24
```